
.globl memmapFastRam
.set memmapFastRam, 0x00000000

.globl memmapCharacterDisplay
.set memmapCharacterDisplay, 0x04000000

# .set xxxxxxxxxxxxxxxxxxxxx, 0x08000000
# .set xxxxxxxxxxxxxxxxxxxxx, 0x0c000000
# .set xxxxxxxxxxxxxxxxxxxxx, 0x10000000
# .set xxxxxxxxxxxxxxxxxxxxx, 0x14000000
# .set xxxxxxxxxxxxxxxxxxxxx, 0x18000000
# .set xxxxxxxxxxxxxxxxxxxxx, 0x1c000000

.globl memmapSlowRam
.set memmapSlowRam, 0x80000000
